### ISSUE TITLE
add : new repo for beginners 

### ISSUE THREAD

**Issue by rohitroy-github** [Piyushhbhutoria/awesome-hacktoberfest-2020#10]
I would like to add a repository to the beginners' list so that new comers can make a contribution to it. The repository is one of mine. 

Additional context
I will be making this contribution in accordance with Hacktoberfest!

**Comment by Piyushhbhutoria** [comment]
you can simply fork and update the readme and raise a PR. I will merge it.

**Comment by rohitroy-github** [comment]
Cool

**Comment by rohitroy-github** [comment]
@Piyushhbhutoria you can have a check!

**Comment by rohitroy-github** [comment]
Please add the hactoberfest labels in the PR !
