### ISSUE TITLE
fix: site sub-heading 

### ISSUE THREAD

**Issue by rohitroy-github** [Piyushhbhutoria/awesome-hacktoberfest-2020#9]
I think the site's subheading should say 2023. I wanna fix that if I'm right! 

This is a screenshot of the issue, I'm referring to! 
![image](https://github.com/Piyushhbhutoria/awesome-hacktoberfest-2023/assets/68563695/9e620190-498a-4610-8332-b2b1ab50f120)

**Additional context**
I will be making this contribution in accordance with Hacktoberfest!

**Comment by Piyushhbhutoria** [comment]
this has been fixed.
